Add ButlerRuleFailedBoard to NotificationType
gregsdennis/Manatee.Trello pull request #344
Opened 2021-02-04 04:23 UTC by techfooninja

I know this repo isn't maintained anymore, but wanted to include this PR in case anyone else ran into the same bug I did. Thanks for all you've done!

2021-02-04 05:01 UTC, gregsdennis commented
Thanks for the PR. I can pull this in. Would you also mind bumping the minor version?

There's also an issue for another event type that's missing.  If you could add that, is appreciate it.

Those two things, then I can merge.

2021-02-04 13:33 UTC, techfooninja commented
Do you know what the other event type is?

2021-02-04 17:33 UTC, gregsdennis commented
https://github.com/gregsdennis/Manatee.Trello/issues/342

2021-02-04 18:09 UTC, techfooninja commented
Awesome, thanks. I just pushed the changes.

2021-02-04 20:57 UTC, gregsdennis requested changes
A couple things. Thanks.

2021-02-04 20:57 UTC, gregsdennis commented on Manatee.Trello/Notification.cs
> +					{NotificationType.CreateCheckItem, n => $"{n.Creator} added checkItem {n.Data.CheckItem} on card {n.Data.Card}" },
I think this was actually an action (`ActionType`).

2021-02-04 20:57 UTC, gregsdennis commented on Manatee.Trello/Manatee.Trello.csproj
> +    <FileVersion>4.3.1.0</FileVersion>
Should be 4.4.0 because you're adding a new member.

2021-02-04 20:57 UTC, gregsdennis commented on Manatee.Trello/Manatee.Trello.csproj
> +    <Version>4.3.1</Version>
4.4.0

2021-02-04 21:07 UTC, techfooninja commented
Resolved your comments. Thanks for the feedback.

2021-02-04 21:28 UTC, gregsdennis approved these changes
Thanks.  I'll figure out what's happening with the build.

2021-02-04 21:33 UTC, techfooninja commented
I think it may be configuration with the account. I think Trello moved to Atlassian auth a while back.

2021-02-05 05:32 UTC, gregsdennis commented
The oauth1 auth still works with the api.  I can run the tests locally.  I'll just update the build. 🤞

2021-02-05 05:53 UTC, merged